# Generated by Django 2.1.10 on 2019-07-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_management', '0003_internshiplocationmodel_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='internships',
            field=models.ManyToManyField(to='intern_management.InternshipLocationModel'),
        ),
    ]
