# Generated by Django 2.1.10 on 2019-07-29 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_internships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='picture',
        ),
    ]
