# Generated by Django 2.1.10 on 2019-08-02 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_studentprofile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='internships',
        ),
    ]
