# Generated by Django 2.1.10 on 2019-08-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_management', '0007_remove_internshiplocationmodel_users'),
        ('users', '0004_remove_studentprofile_internships'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='locations',
            field=models.ManyToManyField(to='intern_management.InternshipLocationModel'),
        ),
    ]
