# Generated by Django 2.1.10 on 2019-08-02 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_studentprofile_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
