# Generated by Django 2.1.10 on 2019-07-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipLocationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=400)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='StudentModel',
        ),
    ]
