# Generated by Django 2.1.10 on 2019-07-16 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intern_management', '0002_auto_20190716_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshiplocationmodel',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
