# Generated by Django 2.1.10 on 2019-07-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_management', '0003_internshiplocationmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshiplocationmodel',
            name='contact_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
