# Generated by Django 2.1.10 on 2019-08-02 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_management', '0004_internshiplocationmodel_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshiplocationmodel',
            name='user',
        ),
    ]
