# Generated by Django 2.1.10 on 2019-08-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_studentprofile_internships'),
        ('intern_management', '0005_remove_internshiplocationmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshiplocationmodel',
            name='users',
            field=models.ManyToManyField(to='users.StudentProfile'),
        ),
    ]
