# Generated by Django 2.1.10 on 2019-08-02 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_management', '0009_internshiplocationmodel_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internshiplocationmodel',
            options={},
        ),
    ]
