# Generated by Django 2.1.10 on 2019-08-03 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_management', '0010_auto_20190802_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internshiplocationmodel',
            options={'permissions': [('can_confirm', 'User can confirm hours for this location')]},
        ),
    ]
