# Generated by Django 2.1.10 on 2019-08-03 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_management', '0012_urltokenmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UrlTokenModel',
        ),
    ]
