# Generated by Django 2.1.10 on 2019-08-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_management', '0016_auto_20190803_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshiplocationmodel',
            name='outstanding_token',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
