# Generated by Django 2.1.10 on 2019-08-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_management', '0019_auto_20190804_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshiplocationmodel',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
