# Generated by Django 2.1.10 on 2019-08-13 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intern_management', '0020_internshiplocationmodel_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedHoursModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='internshiplocationmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='internshiplocationmodel',
            name='manager',
        ),
        migrations.AddField(
            model_name='internshiplocationmodel',
            name='manager',
            field=models.ManyToManyField(null=True, related_name='_internshiplocationmodel_manager_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loggedhoursmodel',
            name='location',
            field=models.ManyToManyField(to='intern_management.InternshipLocationModel'),
        ),
        migrations.AddField(
            model_name='loggedhoursmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
