# Generated by Django 2.1.10 on 2019-08-13 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intern_management', '0021_auto_20190813_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggedhoursmodel',
            name='location',
        ),
        migrations.AddField(
            model_name='loggedhoursmodel',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='intern_management.InternshipLocationModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loggedhoursmodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
