# Generated by Django 2.1.10 on 2019-08-13 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intern_management', '0023_auto_20190813_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshiplocationmodel',
            name='manager',
        ),
        migrations.AddField(
            model_name='internshiplocationmodel',
            name='managers',
            field=models.ManyToManyField(related_name='_internshiplocationmodel_managers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
