# Generated by Django 2.1.10 on 2019-08-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_management', '0024_auto_20190813_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedhoursmodel',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loggedhoursmodel',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
