# Generated by Django 2.1.10 on 2019-08-14 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intern_management', '0025_auto_20190814_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedhoursmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
