# Generated by Django 2.1.11 on 2019-08-19 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intern_management', '0027_auto_20190819_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='location',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='intern_management.InternshipLocationModel'),
            preserve_default=False,
        ),
    ]
