# Generated by Django 2.2.4 on 2019-08-24 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import intern_management.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intern_management', '0032_internshiplocationmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableworkmodel',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internshiplocationmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='location_pictures', validators=[intern_management.validators.validate_image_size]),
        ),
    ]
